# Generated by Django 3.2.12 on 2022-03-27 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time for which object was created.')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Date time for which object was last modified.')),
                ('title', models.CharField(help_text='Title for which task was created.', max_length=100, verbose_name='title task')),
                ('description', models.TextField(help_text='Description for which task was created.', verbose_name='description task')),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'modified_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
